-- POI store for pre-merger Ho Chi Minh City
-- Generated by .codex_tmp/poi_build/step5_split_for_postgres.py

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS poi_schools CASCADE;
CREATE TABLE poi_schools (
    poi_id text PRIMARY KEY,
    poi_type text,
    poi_subtype text,
    name text,
    address_new text,
    address_new_precision text,
    new_ward text,
    new_ward_code text,
    new_province text,
    address_old text,
    old_ward text,
    old_district text,
    old_province text,
    latitude double precision,
    longitude double precision,
    location_precision text,
    geocode_confidence text,
    source text,
    source_url text,
    updated_at timestamptz,
    campus_name text,
    school_level_codes text,
    ownership text,
    student_count integer,
    old_address_confidence text
);

\copy poi_schools (poi_id, poi_type, poi_subtype, name, address_new, address_new_precision, new_ward, new_ward_code, new_province, address_old, old_ward, old_district, old_province, latitude, longitude, location_precision, geocode_confidence, source, source_url, updated_at, campus_name, school_level_codes, ownership, student_count, old_address_confidence) FROM 'data/poi_schools.csv' WITH (FORMAT csv, HEADER true, NULL '');

ALTER TABLE poi_schools ADD COLUMN geom geography(Point, 4326)
    GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED;
-- Nếu bản PostGIS không cho dùng cột sinh tự động, thay hai dòng trên bằng:
--   ALTER TABLE poi_schools ADD COLUMN geom geography(Point, 4326);
--   UPDATE poi_schools SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography;
CREATE INDEX poi_schools_geom_idx ON poi_schools USING GIST (geom);
CREATE INDEX poi_schools_subtype_idx ON poi_schools (poi_subtype);

DROP TABLE IF EXISTS poi_hospitals CASCADE;
CREATE TABLE poi_hospitals (
    poi_id text PRIMARY KEY,
    poi_type text,
    poi_subtype text,
    name text,
    address_new text,
    address_new_precision text,
    new_ward text,
    new_ward_code text,
    new_province text,
    address_old text,
    old_ward text,
    old_district text,
    old_province text,
    latitude double precision,
    longitude double precision,
    location_precision text,
    geocode_confidence text,
    source text,
    source_url text,
    updated_at timestamptz,
    ownership text
);

\copy poi_hospitals (poi_id, poi_type, poi_subtype, name, address_new, address_new_precision, new_ward, new_ward_code, new_province, address_old, old_ward, old_district, old_province, latitude, longitude, location_precision, geocode_confidence, source, source_url, updated_at, ownership) FROM 'data/poi_hospitals.csv' WITH (FORMAT csv, HEADER true, NULL '');

ALTER TABLE poi_hospitals ADD COLUMN geom geography(Point, 4326)
    GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED;
-- Nếu bản PostGIS không cho dùng cột sinh tự động, thay hai dòng trên bằng:
--   ALTER TABLE poi_hospitals ADD COLUMN geom geography(Point, 4326);
--   UPDATE poi_hospitals SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography;
CREATE INDEX poi_hospitals_geom_idx ON poi_hospitals USING GIST (geom);
CREATE INDEX poi_hospitals_subtype_idx ON poi_hospitals (poi_subtype);

DROP TABLE IF EXISTS poi_markets CASCADE;
CREATE TABLE poi_markets (
    poi_id text PRIMARY KEY,
    poi_type text,
    poi_subtype text,
    name text,
    address_new text,
    address_new_precision text,
    new_ward text,
    new_ward_code text,
    new_province text,
    address_old text,
    old_ward text,
    old_district text,
    old_province text,
    latitude double precision,
    longitude double precision,
    location_precision text,
    geocode_confidence text,
    source text,
    updated_at timestamptz,
    manual_review_required boolean
);

\copy poi_markets (poi_id, poi_type, poi_subtype, name, address_new, address_new_precision, new_ward, new_ward_code, new_province, address_old, old_ward, old_district, old_province, latitude, longitude, location_precision, geocode_confidence, source, updated_at, manual_review_required) FROM 'data/poi_markets.csv' WITH (FORMAT csv, HEADER true, NULL '');

ALTER TABLE poi_markets ADD COLUMN geom geography(Point, 4326)
    GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED;
-- Nếu bản PostGIS không cho dùng cột sinh tự động, thay hai dòng trên bằng:
--   ALTER TABLE poi_markets ADD COLUMN geom geography(Point, 4326);
--   UPDATE poi_markets SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography;
CREATE INDEX poi_markets_geom_idx ON poi_markets USING GIST (geom);
CREATE INDEX poi_markets_subtype_idx ON poi_markets (poi_subtype);

-- One view over all three, for the spatial feature job.
CREATE OR REPLACE VIEW pois AS
    SELECT poi_id, poi_type, poi_subtype, name, address_new, address_old,
           old_district, latitude, longitude, geocode_confidence, source, updated_at, geom
      FROM poi_schools
    UNION ALL
    SELECT poi_id, poi_type, poi_subtype, name, address_new, address_old,
           old_district, latitude, longitude, geocode_confidence, source, updated_at, geom
      FROM poi_hospitals
    UNION ALL
    SELECT poi_id, poi_type, poi_subtype, name, address_new, address_old,
           old_district, latitude, longitude, geocode_confidence, source, updated_at, geom
      FROM poi_markets;

-- Example: count POIs within 1 km of a listing point.
-- SELECT poi_type, count(*) FROM pois
--  WHERE ST_DWithin(geom, ST_SetSRID(ST_MakePoint(:lon, :lat), 4326)::geography, 1000)
--  GROUP BY poi_type;
